### ISSUE TITLE
Bosses don't collide

### ISSUE THREAD

**Issue by Sandertv** [diamond-gold/MiniBosses#1]
Hey!
This plugin is really cool (with really I mean REALLY) but I got one suggestions. Right now the bosses do not collide with blocks, they go straight through them and don't seem to be able to jump either... I hope you can make it so they do collide and jump, if that would be done the plugin would be absolutely epic. :)

**Comment by Sandertv** [comment]
Issue in latest version; bosses don't spawn anymore using the /minibosses spawn command

**Comment by Sandertv** [comment]
Oh! since the latest 0.16 MCPE update some meta data stuff changed, making the plugin crash you if you come near the location of a miniboss, could you fix this? :)

**Comment by diamond-gold** [comment]
Plugin crash or client crash? Was there any error messages?

**Comment by Sandertv** [comment]
Client crash, the error says something about class constants not found.

**Comment by diamond-gold** [comment]
Can you provide the exact error message?

**Comment by Sandertv** [comment]
I can't check it again for a couple hours, as I don't have a stable internet connection right now. As soon as I do I'll tell you the error!

**Comment by Sandertv** [comment]
Sorry for the late reply, here it his:
```
Error: Undefined class constant 'DATA_NO_AI'
File: myzip:///MiniBosses-master.zip#MiniBosses-master/src/MiniBosses/Boss
Line: 59
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : MiniBosses v1.0.0

Code:
[50] 		$this->respawnTime = $this->namedtag["respawnTime"];
[51] 		$this->skin = $this->namedtag["skin"];
[52] 		$heldItem = explode(';',$this->namedtag["heldItem"]);
[53] 		$this->heldItem = Item::get($heldItem[0],isset($heldItem[1]) ? $heldItem[1] : 0,isset($heldItem[2]) ? $heldItem[2] : 1,isset($heldItem[3]) ? $heldItem[3] : "");
[54] 	}
[55] 	
[56] 	public function initEntity(){
[57] 		$this->plugin = $this->server->getPluginManager()->getPlugin("MiniBosses");
[58]         parent::initEntity();
[59]         $this->dataProperties[self::DATA_NO_AI] = [self::DATA_TYPE_BYTE, 1];
[60] 		if(isset($this->namedtag->maxHealth)){
[61] 			parent::setMaxHealth($this->namedtag["maxHealth"]);
[62] 			$this->setHealth($this->namedtag["maxHealth"]);
[63] 		}else{
[64] 			$this->setMaxHealth(20);
[65] 			$this->setHealth(20);
[66] 		}
[67]     }
[68] 	
[69] 	public function getName(){
```

**Comment by Sandertv** [comment]
Okay so I did some investigation, and I found out this issue lays in this line: https://github.com/diamond-gold/MiniBosses/blob/master/src/MiniBosses/Boss.php#L182.
In my fork I changed it to `parent::entityBaseTick();` which in fact fixed that issue. It does come with a con though. When knocking back the monsters they kind of 'dash' back to you, which is kinda weird.

**Comment by diamond-gold** [comment]
I just merged your pull request, could you update your link?

**Comment by Sandertv** [comment]
Done!

**Comment by diamond-gold** [comment]
I changed that to parent::entityBaseTick(), the mobs still go through walls, though this time with a 'jerk' movement
mobs also slowed down significantly...

**Comment by Sandertv** [comment]
Hmmm, I must have made a mistake. Let me check.

**Comment by Sandertv** [comment]
Ah! Of course! Just need to add the line $this->checkBlockCollision() before the update move.

**Comment by Sandertv** [comment]
As far as I tested, it seems that with parent::onUpdate() didn't work with $this->checkBlockCollision. I'm not entirely sure.

**Comment by diamond-gold** [comment]
`$this->checkBlockCollision();
		$this->updateMovement();
		parent::entityBaseTick();
		return !$this->closed;`
Is this the last few lines of your onUpdate()?

**Comment by Sandertv** [comment]
Yep, just: `parent::entityBaseTick($currentTick);`

**Comment by diamond-gold** [comment]
Hmmm still go through walls, maybe commit on your fork and let me try it?

**Comment by Sandertv** [comment]
https://github.com/Sandertv/MinibossesTests

I added some experimental things such as lightning, might be cool to check out some time.

**Comment by Sandertv** [comment]
They still walk through walls it seems like with my changes, just no longer get knocked through them.

**Comment by diamond-gold** [comment]
Yep, but they will suddenly just kind of teleport in front you after knockback

**Comment by Sandertv** [comment]
Yeah.
