### ISSUE TITLE
New feature: Blood / Ai (Little modification) ... Working on

### ISSUE THREAD

**Issue by benda95280** [diamond-gold/MiniBosses#15]
Hello,

I'm working to add blood (done), but how i can get the damage done by the player to the Miniboss, in the attack function ?

I've change this line too, because i was thinking it was too easy to kill monster.
$this->knockbackTicks = rand(0,12);

I'm thinking to find a way, when Health under 50%, to have a new moving pattern (5% chance) to get back, move, and attack again.

I'm trying to add Critical Hit too, with particule (Or onscreen msg), and Chance to trigger, in config, but not yet ready with YAML config and add it to entity.

And looking to make a pause to the monster (20% chance) when 3 times hitting without damage receive.

And add "Dodge" (Translation ?:) ) Miss hit, to the monster (Configuration in file possible) ... 
(Not yet checked how to do it)

Thanks.
I hope to send you a PR soon :)

**Comment by EduGH7** [comment]
Why did you add blood?🤔 I just found a plugin for blood after searching a loot, and I think that improving the AI would be better for the players experience 🤣

**Comment by benda95280** [comment]
I've added Blood because it was easy to start with this first modification.
(And my child find this funny)

Il going to check how to improve what i've say below.
Could you tell me how to have damage done ton the entity on attack function ?

**Comment by benda95280** [comment]
First test: https://github.com/benda95280/MiniBosses/commit/11696082bf839a04cf0b34ce2db0e17b7a4ae26d

I'm not very happy for the part of the movement.
I'm looking to find something better ...

**Comment by benda95280** [comment]
Some news:
https://github.com/benda95280/MiniBosses/commit/90787d961b7fe33cae5a2760dda353db84581852
**Correction for the move of Boss + Damage indicator**

Next step:
- Find how to add block attack (Missed)
- Show on Screen "Missed" insted of Damage / Life
- Fix display of the text too close (Some times not visible)
- Find a way because the Boss is to close to the player

**Comment by EduGH7** [comment]
Sorry, but I'm not programmer or something like that, with luck I can configure the plugins and update the API version if I need it🤣🤣 but It's cool your idea, and hope you can improve the AI and add the things that you say like critical hit! I will be watching your news!

**Comment by EduGH7** [comment]
And do you know if the AI of the mobs act like the mobs in first place? I mean, that the slimes attacks jumping, and the entities that flies smash in the ground from the air or the blazes throw you fireballs? I'm curious about that

**Comment by benda95280** [comment]
> Sorry, but I'm not programmer or something like that, with luck I can configure the plugins and update the API version if I need it but It's cool your idea, and hope you can improve the AI and add the things that you say like critical hit! I will be watching your news!

I'm so sad :sob: I was hopping to have some help :cry: 



> And do you know if the AI of the mobs act like the mobs in first place? I mean, that the slimes attacks jumping, and the entities that flies smash in the ground from the air or the blazes throw you fireballs? I'm curious about that

I think to add a new information/TAG to the entity about the move ( Dog / Zombie / Fly) To handle the move, and create a function with all move.
(Like you do for the Autoattack) but i'm not familiary with that yet.

**Comment by EduGH7** [comment]
I'm sure eventually someone will help you ;D and indeed I want to learn about programing this plugins in java but I don't know where to start😅 and I got another idea (I'm not programmer but a little creative 🤣) and is that the bosses have weaknesses, like to the axes, or the swords, or the shovels, even to the fire and stuff like that🤷‍♂️

**Comment by benda95280** [comment]
> I'm sure eventually someone will help you ;D

If someone read this, hope you will write here :)

> and indeed I want to learn about programing this plugins in java but I don't know where to start😅

Sorry, no skill in java

> and I got another idea (I'm not programmer but a little creative 🤣) and is that the bosses have weaknesses, like to the axes, or the swords, or the shovels, even to the fire and stuff like that🤷‍♂️

Should be possible, maybe later i think.
I'll want to work on other thing before, like:
- Can resurrect
- Can spawn earthworms when die (And removed after killed, or 1 minute)

Maybe should write everything somewhere xD

**Comment by EduGH7** [comment]
And your doing all of this for your child?🤣😮

**Comment by benda95280** [comment]
Yes, Small server for them to be able to have some fun.
I've done a little video to show on what i'm working.
https://youtu.be/PfC_CSELWqw

I'm working now on the jump feature, everything seems to be fine, but won't jump.

**Comment by EduGH7** [comment]
When I grow up I want to do the same for my kids 😂 however your server looks cool, I'm doing something different, a custom skyblock like the one of hypixel on computer version. P.D. Are u the same in the slapper issue?

**Comment by benda95280** [comment]
> Are u the same in the slapper issue?

Yes :)

Sorry for the delay, working on some modifications for LuckyBlock Plugin + Textures / TheDropper plugin.

I'm still trying to find a solution for this plugin:
- Everything seems near OK to make mob jump, but won't jump ...
- Trying to make "missed" part of the mob, but don't work as expected, don't know how to prevent damade / cancel damage to the mob.

**Comment by EduGH7** [comment]
And about what is your server exactly?🤔
When I see the plugin I thought they have a normal AI 😂 Did you know any quests plugin, I thought there would be a loot of options but actually I only found 2 that don't work and I... (In sell😂)

**Comment by benda95280** [comment]
> And about what is your server exactly?🤔
MiniGames for my child (many ...)
Money System with Job (Giant Mine + Giant Forest), Adventure World, Cityworld to buy plot and make a City.

> When I see the plugin I thought they have a normal AI 😂
? I'm going to update my currently work.

> Did you know any quests plugin, I thought there would be a loot of options but actually I only found 2 that don't work and I... (In sell😂)
Sorry, not yet checked this type of plugin.

**Comment by EduGH7** [comment]
Oh! Cool😂 I still don't knowing how to make the slappers chat without the name of [Server] :'(

**Comment by benda95280** [comment]
1) Add a plugin to send custom message to a player (addcommand ThePlugin {player} Custom message to say to the player)
2) Create a plugin, with an only one command, usable only with slapper, that could send a message to the player that hit him. /slappersay Hello my friend
_(Example: https://github.com/jojoe77777/SlapperRotation/blob/master/src/SlapperRotation/Main.php)_
Should be possible easyly

**Comment by EduGH7** [comment]
Thanks! I've been worry with school but I'll try to do that😂
Do you know why there are way more plugins for java edition and almost any for pocketmine?😥
