### ISSUE TITLE
Do you accept plugin in customization?

### ISSUE THREAD

**Issue by Atara6431** [diamond-gold/MiniBosses#30]
Do you customize the connector? There are some function expansion based on this plug-in or others. We have opened an RPG server. At present, there are about 700 players in the server cluster. I will pay for each new content, such as PayPal

你接插件定制吗？有一些基于这个插件的功能拓展或者其他的，我们开了一个RPG服务器，目前服务器群有700人左右，我会为每一个新增内容付费，paypal之类的都可以，非常期待能和您合作！

**Comment by diamond-gold** [comment]
让我们更深入的洽谈吧

**Comment by Atara6431** [comment]
哪种社交软件是你常用的

**Comment by Atara6431** [comment]
see your wechat please

**Comment by Atara6431** [comment]
我已经因为这bug关服三天了啊
