### ISSUE TITLE
Question: How to change 

### ISSUE THREAD

**Issue by ricky074game** [diamond-gold/MiniBosses#32]
For your plugin, I want to create a player entity with a custom skin and geometry.
I understand how to put the geometry in, but I don't understand how to put the skin in.
How do I convert a .png file skin into data?

**Comment by diamond-gold** [comment]
It is currently not possible to convert from png. You need to set the skin on yourself

**Comment by ricky074game** [comment]
How do I set the skin on myself?

**Comment by diamond-gold** [comment]
It is now possible with this [script](https://github.com/diamond-gold/MiniBosses/wiki/Convert-skin-cape-from-png-to-config)
