### ISSUE TITLE
Falls through ground

### ISSUE THREAD

**Issue by SuperDude36** [diamond-gold/MiniBosses#5]
This worked great on my test server, now when it spawns it falls through ground.

**Comment by diamond-gold** [comment]
Which server software are you using?

**Comment by SuperDude36** [comment]
Genisys

**Comment by SuperDude36** [comment]
Ill check the bug again

**Comment by yuriloli** [comment]
Did you fix?

**Comment by Sandertv** [comment]
See #6

**Comment by yuriloli** [comment]
@Sandertv Human's still fall through the ground but other mobs are okay

**Comment by Sandertv** [comment]
I'll see what I can do @yuriloli
